WIP

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,10 +1,8 @@
 #!/usr/bin/env bash
 
 # TODO: might need to check for /dev/dri and remove it from compose if not found
-#        people having issues with permission on that dir (add plex to video group?)
-# TODO: various configurations using cli
 # TODO: Test permissions and integration
-# TODO: add pihole
+# TODO: create new user and make all containers run as non-root
 
 
 set -o errexit
@@ -13,6 +11,18 @@ set -o pipefail
 
 
 readonly LOG_FILE=/tmp/nateflix-$(date +%Y%m%d%H%M%S).log
+declare -A SERVICE_NAMES
+SERVICE_NAMES["portal"]="Portal:portal:1"
+SERVICE_NAMES["nzbget"]="NZBGet:newz:1"
+SERVICE_NAMES["deluge"]="Deluge:torrents:1"
+SERVICE_NAMES["plex"]="Plex:watch:0"
+SERVICE_NAMES["plexstats"]="Plex Stats:stats:1"
+SERVICE_NAMES["ombi"]="OMBI:request:0"
+SERVICE_NAMES["pihole"]="PiHole:pihole:1"
+SERVICE_NAMES["jackett"]="Jackett:jackett:1"
+SERVICE_NAMES["sonarr"]="Sonarr:shows:1"
+SERVICE_NAMES["radarr"]="Radarr:movies:1"
+SERVICE_NAMES["lidarr"]="Lidarr:music:1"
 
 
 check_installed()
@@ -26,9 +36,16 @@ check_installed()
 
 check_ports()
 {
-  local ports="53 67 80 443 38258 32400 3005 8324 32469 1900 32410 32412 32413 32414"
+  declare bind_ip="${1:-}"
+
+  if [[ -z ${bind_ip} ]]; then
+    bind_ip=$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')
+  fi
+
+  #38258
+  local ports="53 67 80 443 32400 3005 8324 32469 1900 32410 32412 32413 32414"
   local used=''
-  local openPorts=$(lsof -Pi -n | grep -Pv "\-\>|127\.0\.0\." | grep -v "COMMAND")
+  local openPorts=$(lsof -Pi -n | grep -Pv "\-\>" | grep -P "${bind_ip}|\*:" | grep -v "COMMAND")
 
   for port in $ports; do
     local result=$(grep ":${port} " <<< "${openPorts}" | tail -n 1)
@@ -159,15 +176,24 @@ cleanup()
 
 wait_for_service()
 {
-  declare port="$1" url_path="$2" status="$3" content="$4" retries="${5:-20}"
+  declare service="$1" url_path="$2" status="$3" content="$4" retries="${5:-20}"
 
-  local url="http://${ADVERTISE_IP}:${port}${url_path}"
-  local http_status='0'
-  local http_content=''
-  local out=''
+  echo "Waiting for service to become available..."
+  local hostname=$(echo ${SERVICE_NAMES["${service}"]} | cut -d ':' -f 2)
+  local url="https://${hostname}.${DOMAIN}${url_path}"
+  local http_status="0"
+  local http_content=""
+  local out=""
+  local use_password=$(echo ${SERVICE_NAMES["${service}"]} | cut -d ':' -f 3)
 
   while [[ ${http_status} != ${status} || ! ${http_content} =~ ${content} ]]; do
-    out=$(curl -k --silent -L -w "\n%{http_code}" "${url}" || true)
+    if [[ ${use_password} == "1" ]]; then
+      out=$(curl -k --silent -L -w "\n%{http_code}" \
+            --netrc-file <(cat <<<"machine ${hostname}.${DOMAIN} login ${PORTAL_USERNAME} password ${PORTAL_PASSWORD}") \
+            "${url}" || true)
+    else
+      out=$(curl -k --silent -L -w "\n%{http_code}" "${url}" || true)
+    fi
     http_status="${out##*$'\n'}"
     http_content="${out%$'\n'*}"
     retries=$((${retries}-1))
@@ -312,23 +338,25 @@ gather_required_config()
   if [[ -z ${PORTAL_USERNAME:-} && -z ${PORTAL_PASSWORD:-} ]]; then
     echo
     echo "Set credentials for web access to system portal"
-    while [[ -z ${PORTAL_USERNAME:-} ]]; do
+    while [[ -z ${PORTAL_USERNAME:-} || ${PORTAL_PASSWORD:-"1"} != ${PORTAL_CONFIRM_PASSWORD:-"2"} ]]; do
       read -ep "Portal Username: " PORTAL_USERNAME
-      if [[ -z ${PORTAL_USERNAME} ]]; then
-        echo "Portal username is required"
-      else
-        PORTAL_PASSWORD=$(openssl passwd -apr1 -quiet 2>/dev/null || true)
-        while [[ -z ${PORTAL_PASSWORD} ]]; do
-          PORTAL_PASSWORD=$(openssl passwd -apr1 -quiet 2>/dev/null || true)
-        done
+      read -esp "Plex password: " PORTAL_PASSWORD
+      echo
+      read -esp "Confirm password: " PORTAL_CONFIRM_PASSWORD
+      echo
+
+      if [[ -z ${PORTAL_USERNAME} || -z ${PORTAL_PASSWORD} ]]; then
+        echo "Portal username and password are required"
+      elif [[ ${PORTAL_PASSWORD} != ${PORTAL_CONFIRM_PASSWORD} ]]; then
+        echo "Passwords do not match"
       fi
     done
   else
     echo "PORTAL_CREDENTIALS: ${PORTAL_USERNAME}:********"
-    PORTAL_PASSWORD=$(echo ${PORTAL_PASSWORD}|openssl passwd -stdin -apr1 -quiet 2>/dev/null || true)
   fi
 
-  export PORTAL_CREDS="${PORTAL_USERNAME}:${PORTAL_PASSWORD}"
+  export PORTAL_PASSWORD
+  export PORTAL_CREDS="${PORTAL_USERNAME}:$(echo ${PORTAL_PASSWORD}|openssl passwd -stdin -apr1 -quiet 2>/dev/null || true)"
 
   if [[ -z ${VPN_USERNAME:-} && -z ${VPN_PASSWORD:-} ]]; then
     echo
@@ -354,24 +382,11 @@ gather_required_config()
   if [[ -z ${ADVERTISE_IP:-} ]]; then
     local ip=$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')
     export ADVERTISE_IP=$(get_value "Advertise IP" "${ip}")
-    # echo "Select the advertise IP address. This allows uPnP to work properly"
-    # local devices=$(ip -f inet link show | grep 'state UP' | grep -Pv "docker|lo:" | cut -d ' ' -f 2 | sed 's/.$//')
-    # local ips=""
-    # local options=""
-    # for device in ${devices}; do
-    #   local ip=$(ip -f inet addr show ${device} | grep -Po 'inet \K[\d.]+')
-    #   ips="${ips:-}${ip} "
-    #   options="${options}${device}: ${ip}|"
-    # done
-    #
-    # echo "Available advertising addresses"
-    # echo "${options//|/$'\n'}" | column -c 2 -t
-    # echo
-    #
-    # export ADVERTISE_IP=$(get_value "Advertise IP" "${ip[0]}")
   else
     echo "ADVERTISE_IP: ${ADVERTISE_IP}"
   fi
+
+  check_ports "${ADVERTISE_IP}"
 
   if [[ -z ${DOMAIN:-} ]]; then
     export DOMAIN=$(get_value "Nateflix domain name (FQDN if you have one)" "$(hostname).local")
@@ -438,17 +453,16 @@ install()
 docker_stop()
 {
   declare service="$1"
-  docker stop "${service}" > /dev/null 2>&1
-  docker rm "${service}" > /dev/null 2>&1
+  docker-compose stop "${service}"
 }
 
 docker_start()
 {
-  declare service="$1" port="$2" url="$3" status="$4" \
-          content="$5" retries="${6:-20}" dont_stop="${7:-0}"
+  declare service="$1" url="$2" status="$3" \
+          content="$4" retries="${5:-20}" dont_stop="${6:-0}"
 
-  docker-compose run -d --publish=${ADVERTISE_IP}:38258:${port} --name "${service}" "${service}"
-  wait_for_service 38258 "${url}" ${status} "${content}" ${retries}
+  docker-compose up -d "${service}"
+  wait_for_service "${service}" "${url}" ${status} "${content}" ${retries}
 
   if [[ ${dont_stop} == 0 ]]; then
     docker_stop "${service}"
@@ -471,7 +485,7 @@ configure_lidarr()
     return
   fi
 
-  docker_start "lidarr" 8686 "" 200 "Lidarr" 30
+  docker_start "lidarr" "" 200 "Lidarr" 30
 
   sqlite3 "${dbFile}" "insert into Config (Key,Value) values ('autounmonitorpreviouslydownloadedtracks', 'True')"
   sqlite3 "${dbFile}" "insert into Config (Key,Value) values ('deleteemptyfolders', 'True')"
@@ -512,9 +526,7 @@ configure_plex()
     exit 1;
   fi
 
-  docker-compose up -d plex
-  wait_for_service 32400 "/web/index.html" 200 "Plex" 500
-  docker-compose stop plex
+  docker_start "plex" "/web/index.html" 200 "Plex" 500
 }
 
 configure_nzbget()
@@ -533,7 +545,7 @@ configure_nzbget()
     return
   fi
 
-  docker_start "nzbget" 6789 "" 401 "" 10
+  docker_start "nzbget" "" 401 "" 10
 
   sed -i -e "s/^\(ControlUsername\).\+$/\1=/g" "${configFile}"
   sed -i -e "s/^\(ControlPassword\).\+$/\1=/g" "${configFile}"
@@ -543,9 +555,10 @@ make_api_call()
 {
   declare api_key="$1" url="$2" data="$3"
 
-  curl -Ls -H 'Content-Type: application/json' \
+  # --netrc-file <(cat <<<"machine request.${DOMAIN} login ${PORTAL_USERNAME} password ${PORTAL_PASSWORD}") \
+  curl -Ls -k -H 'Content-Type: application/json' \
        -H "ApiKey: ${api_key}" \
-       -d "${data}" "http://${ADVERTISE_IP}:38258/api/v1/${url}"
+       -d "${data}" "https://request.${DOMAIN}/api/v1/${url}"
 }
 
 configure_ombi()
@@ -563,7 +576,7 @@ configure_ombi()
     return
   fi
 
-  docker_start "ombi" 5000 "" 200 "Ombi" 20 1
+  docker_start "ombi" "" 200 "Ombi" 20 1
 
   local apiKey=$(grep -aioe '"ApiKey":"[^"]*' "${CONFIG_DIR}/ombi/Ombi.db" | cut -c 11-)
   local sonarrKey=$(cat "${CONFIG_DIR}/sonarr/config.xml" | grep -aioe "<ApiKey>[^<]*" | cut -c 9-)
@@ -690,7 +703,7 @@ configure_sonarr()
     return
   fi
 
-  docker_start "sonarr" 8989 "" 200 "Sonarr" 20
+  docker_start "sonarr" "" 200 "Sonarr" 20
 
   sqlite3 "${dbFile}" "insert into Config (Key,Value) values ('cleanupmetadataimages', 'False')"
   sqlite3 "${dbFile}" "insert into Config (Key,Value) values ('removecompleteddownloads', 'True')"
@@ -718,7 +731,7 @@ configure_radarr()
     return
   fi
 
-  docker_start "radarr" 7878 "" 200 "Radarr" 20
+  docker_start "radarr" "" 200 "Radarr" 20
 
   sqlite3 "${dbFile}" "insert into Config (Key,Value) values ('cleanupmetadataimages', 'False')"
   sqlite3 "${dbFile}" "insert into Config (Key,Value) values ('removecompleteddownloads', 'True')"
@@ -730,34 +743,35 @@ configure_radarr()
   sed -i -e "s/<\/Config>/<AnalyticsEnabled>False<\/AnalyticsEnabled>\n<\/Config>/" "${CONFIG_DIR}/radarr/config.xml"
 }
 
-configure_plexstats()
-{
-  echo
-  echo
-  echo "**************************"
-  echo "* CONFIGURING PLEX STATS *"
-  echo "**************************"
-  echo
-
-  log "INFO" "Configuring Plex Stats"
-  local configFile="${CONFIG_DIR}/plexstats/config.ini"
-  if [[ -f "${configFile}" ]]; then
-    log "INFO" "Plex Stats already configured; skipping..." 1
-    return
-  fi
-
-  docker_start "plexstats" 8181 "" 200 "Tautulli - Welcome" 500
-
-  sed -i -e "s/^\(pms_url\) =.\+$/\1 = http:\/\/plex:32400/g" "${configFile}"
-  sed -i -e "s/^\(pms_name\) =.\+$/\1 = ${DOMAIN}/g" "${configFile}"
-  sed -i -e "s/^\(pms_plexpass\) =.\+$/\1 = 1/g" "${configFile}"
-  sed -i -e "s/^\(pms_port\) =.\+$/\1 = 32400/g" "${configFile}"
-  sed -i -e "s/^\(pms_platform\) =.\+$/\1 = Linux/g" "${configFile}"
-  sed -i -e "s/^\(pms_ip\) =.\+$/\1 = plex/g" "${configFile}"
-  sed -i -e "s/^\(launch_browser\) =.\+$/\1 = 0/g" "${configFile}"
-  sed -i -e "s/^\(show_advanced_settings\) =.\+$/\1 = 1/g" "${configFile}"
-  sed -i -e "s/^\(pms_logs_folder\) =.\+$/\1 = \/logs/g" "${configFile}"
-}
+# configure_plexstats()
+# {
+#   echo
+#   echo
+#   echo "**************************"
+#   echo "* CONFIGURING PLEX STATS *"
+#   echo "**************************"
+#   echo
+#
+#   log "INFO" "Configuring Plex Stats"
+#   local configFile="${CONFIG_DIR}/plexstats/config.ini"
+#   if [[ -f "${configFile}" ]]; then
+#     log "INFO" "Plex Stats already configured; skipping..." 1
+#     return
+#   fi
+#
+#   docker_start "plexstats" "/welcome" 200 "Tautulli - Welcome" 500
+#
+#   sed -i -e "s/^\(pms_url\) =.\+$/\1 = http:\/\/plex:32400/g" "${configFile}"
+#   sed -i -e "s/^\(pms_url_manual\) =.\+$/\1 = 1/g" "${configFile}"
+#   sed -i -e "s/^\(pms_name\) =.\+$/\1 = ${DOMAIN}/g" "${configFile}"
+#   sed -i -e "s/^\(pms_plexpass\) =.\+$/\1 = 1/g" "${configFile}"
+#   sed -i -e "s/^\(pms_port\) =.\+$/\1 = 32400/g" "${configFile}"
+#   sed -i -e "s/^\(pms_platform\) =.\+$/\1 = Linux/g" "${configFile}"
+#   sed -i -e "s/^\(pms_ip\) =.\+$/\1 = plex/g" "${configFile}"
+#   sed -i -e "s/^\(launch_browser\) =.\+$/\1 = 0/g" "${configFile}"
+#   sed -i -e "s/^\(show_advanced_settings\) =.\+$/\1 = 1/g" "${configFile}"
+#   sed -i -e "s/^\(pms_logs_folder\) =.\+$/\1 = \/logs/g" "${configFile}"
+# }
 
 configure_deluge()
 {
@@ -774,7 +788,7 @@ configure_deluge()
     return
   fi
 
-  docker_start "deluge" 8112 "" 200 "Deluge" 20 1
+  docker_start "deluge" "" 200 "Deluge" 20 1
   while [[ ! -f "${CONFIG_DIR}/deluge/auth" ]]; do
     sleep 1s
   done
@@ -852,9 +866,12 @@ configure_pihole()
 #     return
 #   fi
 #
-#   docker_start "jackett" 9117 "" 200 "awdawdadw" 20
+#   docker_start "jackett" "/UI/Dashboard" 200 "Jackett" 20
 #
-#   export JACKETT_APIKEY=$(grep -aioe '"APIKey": "[^"]*' "${configFile}" | cut -c 12-)
+#   sed -i -e 's/\(^.*"AllowExternal": \).*[^,]\(,\)\{0,1\}$/\1true\2/g' \
+#       -e 's/\(^.*"BlackholeDir": \).*[^,]\(,\)\{0,1\}$/\1"\/torrents"\2/g' \
+#       -e 's/\(^.*"UpdateDisabled": \).*[^,]\(,\)\{0,1\}$/\1true\2/g' \
+#       -e 's/\(^.*"UpdatePrerelease": \).*[^,]\(,\)\{0,1\}$/\1false\2/g' "${configFile}"
 # }
 
 build_and_configure()
@@ -882,10 +899,34 @@ build_and_configure()
   configure_sonarr
   configure_radarr
   configure_ombi
-  configure_plexstats
+  # configure_plexstats
   configure_deluge
 }
 
+show_complete()
+{
+  echo
+  echo
+  echo "Installation complete"
+  echo
+  echo "You may need to perform some extra setup steps in each application"
+  echo "The following domains might also need to be added to your hosts file"
+  echo "You can also point your DNS to this server and your domain will resolve"
+  echo
+  echo "NOTE: For now, links generated in jackett will need to be changed manually"
+  echo "to 'http' instead of 'https'"
+  echo
+
+  local content=""
+  for service in "${SERVICE_NAMES[@]}"; do
+    local display_name=$(echo "${service}" | cut -d ':' -f 1)
+    local hostname=$(echo "${service}" | cut -d ':' -f 2)
+    content="${content}${display_name},https://${hostname}.${DOMAIN}|"
+  done
+
+  echo "${content//|/$'\n'}" | column -s ',' -t
+  echo
+}
 
 if [[ ${EUID} != 0 ]]; then
    echo "This script must be run as root"
@@ -912,31 +953,9 @@ install
 # Build images and configure programs
 build_and_configure
 
-
-echo
-echo
-echo "Installation complete"
-echo
-echo
-
 docker-compose up -d
 
-echo
-echo "You may need to perform some extra setup steps in each application"
-echo "The following domains might also need to be added to your hosts file"
-echo
-echo "NZBGet:     https://newz.${DOMAIN}"
-echo "Plex:       https://watch.${DOMAIN}"
-echo "Plex Stats: https://stats.${DOMAIN}"
-echo "Lidarr:     https://music.${DOMAIN}"
-echo "Sonarr:     https://shows.${DOMAIN}"
-echo "Radarr:     https://movies.${DOMAIN}"
-echo "OMBI:       https://request.${DOMAIN}"
-echo "Deluge:     https://torrents.${DOMAIN}"
-echo "Portal:     https://portal.${DOMAIN}"
-echo "PiHole:     https://pihole.${DOMAIN}"
-echo "Jakcett:    https://jackett.${DOMAIN}"
-echo
+show_complete
 
 exit $?
 
